version: "3.6"
services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres  
  lab:
      build: ./lab
      ports:
          - "8081:8888"
      environment:
          JUPYTER_NO_PASSWORD: "true"
      volumes:
          - ./lab/work:/home/jupyter/work
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0.cli-migrations
    ports:
    - "8080:8000"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: datastack
      HASURA_GRAPHQL_SERVER_PORT: 8000
volumes:
  db_data: